spring.application.name=doomscroll-backend


spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/doomscroll}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:doomscroll}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:doomscroll}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true